@hostname =  http://localhost:7000/teachers

GET {{hostname}}

###

GET {{hostname}}/2

###

POST {{hostname}}/register
Content-Type: application/json

{   
    "name": "gaurav",
    "password" : "12345678"
}

###

POST {{hostname}}/login/2
Content-Type: application/json


{   
    "name": "gaurav",
    "password" : "1234567"
}

###

PUT {{hostname}}/edit/2
Content-Type: application/json

{   
    "name": "gaurav kapurkar",
    "password" : "12345678"
}

###

DELETE {{hostname}}/delete/2

###